### PR TITLE
Remove starting lag from smoothed strokes

### PR DESCRIPTION
**Pull request by LionsPhil**
The current smoother causes a pretty nasty positional lag to the start of strokes, which makes it hard to accurately position them to connect with other strokes, e.g. drawing a set of lines radiating from a central point.

Have smoothing effectively start at zero and ramp up as more points become available so strokes start where the cursor first touches down.

Partially relates to #179, but the smoother is still just a plain unweighted average.

(I think in future it might be worth looking at having the smoother buffer up some move events so it can still use as many points as possible, but cause *temporal* lag instead, e.g. when you have a full buffer suddenly canvasview can drain that many moves from the smoother, after which it is back to one point added, one (lagged) move received.)

### CODE REVIEW

**Comment by callaa** [comment]
Thanks, I'll take a look at this. I just released version 1.0 and started a new stable branch. Since this does not affect the protocol and is a small change, I'll probably merge it to *stable-1.x* so it can be part of the next (1.0.1) release.

Buffering hovering pointer events is a good idea. MyPaint does that too, although for brush dynamics rather than stabilizing, I think.

**Comment by LionsPhil** [comment]
I'll rebase this onto 1.0, with another tweak commit or two. Doing them separately to get the effect of each change in isolation, but I can squash them down if you'd rather since they're individually tiny.

**Comment by callaa** [comment]
No need to rebase or squash since there will be a merge commit anyway.

**Comment by LionsPhil** [comment]
OK, that's the last of them for now, then. Afraid there's a little bit of thrash where I reintroduced latestPoint() after removing it earlier.

**Pull request merged**
